CREATE TABLE `purchase_adjustments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`quotationId` int NOT NULL,
	`orderId` int,
	`purchaseGroupId` varchar(50),
	`unitId` int,
	`quotationItemId` int NOT NULL,
	`productName` varchar(500) NOT NULL,
	`quantity` decimal(12,3) NOT NULL,
	`unit` varchar(20) NOT NULL,
	`recommendedSupplierId` int NOT NULL,
	`recommendedSupplierName` varchar(200) NOT NULL,
	`recommendedUnitPrice` decimal(12,4) NOT NULL,
	`recommendedTotal` decimal(14,2) NOT NULL,
	`recommendedBrand` varchar(200),
	`recommendedReason` varchar(500),
	`cheapestSupplierId` int,
	`cheapestSupplierName` varchar(200),
	`cheapestUnitPrice` decimal(12,4),
	`selectedSupplierId` int NOT NULL,
	`selectedSupplierName` varchar(200) NOT NULL,
	`selectedUnitPrice` decimal(12,4) NOT NULL,
	`selectedTotal` decimal(14,2) NOT NULL,
	`selectedBrand` varchar(200),
	`impactValue` decimal(14,2) NOT NULL,
	`impactPct` decimal(8,2) NOT NULL,
	`justificationCategory` varchar(100) NOT NULL,
	`justificationText` text NOT NULL,
	`userId` int NOT NULL,
	`userName` varchar(200) NOT NULL,
	`userEmail` varchar(200),
	`optimizationRule` varchar(200),
	`adjustmentStatus` enum('active','cancelled') NOT NULL DEFAULT 'active',
	`closedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `purchase_adjustments_id` PRIMARY KEY(`id`)
);
