CREATE TABLE `emergency_purchase_requests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`originalOrderId` int NOT NULL,
	`quotationId` int,
	`requestedBy` int NOT NULL,
	`requestedByName` varchar(255),
	`requestedByEmail` varchar(320),
	`status` enum('pending_approval','approved','rejected','expired') NOT NULL DEFAULT 'pending_approval',
	`emergencySupplierId` int NOT NULL,
	`emergencySupplierName` varchar(300),
	`invoicePhotoUrl` text,
	`nfAnalysis` json,
	`deficitItems` json,
	`justification` text NOT NULL,
	`totalEstimated` decimal(14,2),
	`approvalToken` varchar(100),
	`approvalTokenExpiresAt` timestamp,
	`approvedBy` int,
	`approvedAt` timestamp,
	`rejectionReason` text,
	`generatedOrderId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `emergency_purchase_requests_id` PRIMARY KEY(`id`),
	CONSTRAINT `emergency_purchase_requests_approvalToken_unique` UNIQUE(`approvalToken`)
);
